'use client';

import { useState } from 'react';
import { collection, getDocs, deleteDoc, doc } from 'firebase/firestore';
import { ref, deleteObject } from 'firebase/storage';
import { db, storage } from '@/lib/firebase';
import { Complaint } from '@/types';

export default function CleanupPage() {
    const [status, setStatus] = useState<string>('Idle');
    const [isCleaning, setIsCleaning] = useState(false);

    const cleanData = async () => {
        try {
            setIsCleaning(true);
            setStatus('Fetching complaints...');

            const complaintsRef = collection(db, 'complaints');
            const snapshot = await getDocs(complaintsRef);

            setStatus(`Found ${snapshot.size} complaints. Deleting...`);

            let deletedCount = 0;
            let errorCount = 0;

            for (const docSnapshot of snapshot.docs) {
                const data = docSnapshot.data() as Complaint;

                // 1. Delete Image from Storage
                if (data.imageUrl) {
                    try {
                        // Create a reference from the HTTPS URL
                        // Note: valid for download URLs generated by Firebase Storage
                        const imageRef = ref(storage, data.imageUrl);
                        await deleteObject(imageRef);
                        console.log(`Deleted image for ${docSnapshot.id}`);
                    } catch (e) {
                        console.error(`Failed to delete image for ${docSnapshot.id}:`, e);
                        // Continue even if image delete fails (maybe it was already deleted)
                    }
                }

                // 2. Delete Document from Firestore
                try {
                    await deleteDoc(doc(db, 'complaints', docSnapshot.id));
                    deletedCount++;
                } catch (e) {
                    console.error(`Failed to delete doc ${docSnapshot.id}:`, e);
                    errorCount++;
                }

                setStatus(`Progress: ${deletedCount}/${snapshot.size} deleted. (${errorCount} errors)`);
            }

            setStatus(`Done! Deleted ${deletedCount} complaints. Errors: ${errorCount}.`);

        } catch (error) {
            console.error('Fatal error during cleanup:', error);
            setStatus(`Error: ${(error as Error).message}`);
        } finally {
            setIsCleaning(false);
        }
    };

    return (
        <div className="min-h-screen flex flex-col items-center justify-center bg-gray-900 text-white p-4">
            <h1 className="text-3xl font-bold mb-6">Data Cleanup Utility</h1>
            <p className="mb-4 text-gray-300">
                This tool will delete ALL data from the 'complaints' collection and associated images.
                <br />
                <strong className="text-red-500">WARNING: This cannot be undone.</strong>
            </p>

            <div className="mb-6 p-4 bg-gray-800 rounded w-full max-w-md text-center">
                <p className="font-mono text-sm">{status}</p>
            </div>

            <button
                onClick={cleanData}
                disabled={isCleaning}
                className={`px-6 py-3 rounded font-bold transition-colors ${isCleaning
                        ? 'bg-gray-600 cursor-not-allowed'
                        : 'bg-red-600 hover:bg-red-700 text-white'
                    }`}
            >
                {isCleaning ? 'Cleaning...' : 'DELETE ALL DATA'}
            </button>
        </div>
    );
}
